markdown: kramdown
title: "CoilSnake"
latest_version: "4.0"
windows_download_url: "http://bit.ly/2m5xodt"
social_media_links:
  twitter: https://twitter.com/_mrtenda
  github: https://github.com/mrtenda/CoilSnake
